// <auto-generated />
namespace Articles_UserBased.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_SuggestedBy_To_Article : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_SuggestedBy_To_Article));
        
        string IMigrationMetadata.Id
        {
            get { return "201912131122268_Add_SuggestedBy_To_Article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
